### PR TITLE
Feat/sk 59

### PR DESCRIPTION
**Pull request by hc-roswell**
@good-idea Could you please review this PR and let us know if there are any issues before we deploy to test Facebook pixel tracking and product catalog? Thanks.

Here are two new .env variables:
# Factbook Pixel
FB_PIXEL_ID=280594976420713
FB_PRDOUCT_CATALOG_ID=872214760030203

Also here are some issues that we observe after we pull from main.
1) When product links under 'shop Best Sellers' is pressed the whole page scroll bar gone and when you release it returns. Sometimes it goes to designated product page sometimes it takes a few tries to trigger the event. (The delay is more pronounced on the dev instance )

2) When select an option on the size dropdown the page url does not refresh (it happens on the live site)

3) Warning: Prop `className` did not match. Server: "sc-cxpRKc Text__createTextBase-sc-1yzgsbh-0 bRdxOj bWpBEb" Client: "sc-cxpRKc Text-sc-1yzgsbh-0 bRdxOj kEYNAn"

4)  Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>. 

5) Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>

### CODE REVIEW

**Review by good-idea — APPROVED** [review]

**Comment by good-idea** [comment]
This all looks great, thank you!

The vercel deployment failed because it was missing the new environment variables. I've added these, but in case you need to do it in the future, it's pretty straightforward:

image

> When product links under 'shop Best Sellers' is pressed the whole page scroll bar gone and when you release it returns. Sometimes it goes to designated product page sometimes it takes a few tries to trigger the event. (The delay is more pronounced on the dev instance )

Do you know of any instances on production where this is occurring? The dev site is slow when navigating as its pages aren't cached... Although it is *particularly* slow, which is annoying. I've been meaning to look into it but it hasn't been a priority.

> When select an option on the size dropdown the page url does not refresh (it happens on the live site)

Odd, it should be doing this on dev... I'll make an issue

> Warning: Prop className did not match. Server: "sc-cxpRKc Text__createTextBase-sc-1yzgsbh-0 bRdxOj bWpBEb" Client: "sc-cxpRKc Text-sc-1yzgsbh-0 bRdxOj kEYNAn"

This is an annoying SSR + styled-components thing. It doesn't really affect anything, and is another low-priority thing.

> Warning: Use the defaultValue or value props on instead of setting selected on .

I believe this is an issue with my changes to the currency selector... it still works but it's not the way that React likes it done. I'll fix this.

> Warning: validateDOMNesting(...): cannot appear as a descendant of

This is caused by some of the Image + Text blocks --- they all have `<a>` tags wrapping them, and there are more `<a>` tags nested within (for instance when one has a CTA component)`. It's invalid HTML, but still works, and is a sticky thing to solve for although now that I'm thinking about it I just had a good idea..

**Comment by good-idea** [comment]
Please go ahead and merge whenever you're ready!

**Comment by hc-roswell** [comment]
Hey Joseph,
	
	Thank you so much for taking the time to respond. 

>>Do you know of any instances on production where this is occurring? The dev site is slow when navigating as its pages aren't cached... Although it is particularly slow, which is annoying. I've been meaning to look into it but it hasn't been a priority.

I think it is Firefox (Mac Developer Edition) that has this weird behavior that does not happen in Chrome. It is especially obvious when you click and hold and try to swipe and the whole carousel just follows your cursor. Overall if you just click and release the mouse it is instantaneous on the live site. But I am constantly having a hard time ( even in Chrome ) trying to click on a product and land on a detail page.


>> Odd, it should be doing this on dev... I'll make an issue

Please check my local instance here for the issue: https://spinellikilcollin.ngrok.io/products/hyacinth?v=Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8yMDQ3MzQzNjUzNjkzMA%3D%3D <https://spinellikilcollin.ngrok.io/products/hyacinth?v=Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8yMDQ3MzQzNjUzNjkzMA==>
I hope it is not the changes that I made that have caused this issue.

hc

**Comment by good-idea** [comment]
Converted this to a draft for the moment ~ ~

Could you create a new issue here in the repo for the carousel swiping / linking issue?

I'll take a look at the variant URL not updating right now and push an update to this branch. Once that's fixed, everything should be ready to go.

**Comment by hc-roswell** [comment]
Hey Joseph,

	Thank you. Will do.

hc

**Comment by hc-roswell** [comment]
> Could you create a new issue here in the repo for the carousel swiping / linking issue?

https://github.com/good-idea/spinellikilcollin.com/issues/76

**Pull request merged**
