### PR TITLE
Feat/bambuser2

### PR DESCRIPTION
**Pull request by hc-roswell**
Bambuser<>Shopify full integration; Facebook Pixel View Content Event; Does NOT include pulling recent changes from develop branch (deploys without errors)

### CODE REVIEW

**Review by good-idea — CHANGES_REQUESTED** [review]
I know there are a lot of comments in here, but overall this PR is really great! Thank you for following the project structure closely.

Please take a look at [this PR](https://github.com/good-idea/spinellikilcollin.com/pull/84) and merge it into this branch.

I'll be on Slack if you have any questions -- I'm sorry that I have been somewhat absent lately!

**Comment by hc-roswell** [comment]
Hey Joseph,
	Thank you so much for providing all the information. I would love to have a conversation about integrating Bambuser with Sanity and the overall strategy to grab the correct variant to display thumbnail in Bambuser product dashboard and the right id for Facebook Pixel ViewContent event tracking. Thanks.

hc



Issues:
a. Bambuser live show and archive structure (1, 2, 3, 14)

There are two separate types of strucutre, one being the live show with auto play funcitionality (or disabled) and then the archived show structure. Our main concetration should only focus on the live show for now, and please let’s have conversation about how to integrate Bambuser into Sanity. If we are tasked to tackle Sanity integration then we would love to have a conversation about the whole workflow. Thanks.

b. Bambuser scraping (10, 11, 12, 13)


c. Bambuser documentation (8)

Here is an example of how Bambuser initialize a show. If a button selector is provided to the “node” property when instializing Bambuser user has to click on the button in order to trigger the show. But if you omit the node property the show will play automatically.

window.initBambuserLiveShopping({ showId: 'BAMBUSER-LIVESHOPPING-SHOW-ID-HERE', node: document.getElementById('liveshopping-123'), type: 'overlay', });

d. Facebook pixel reporting (4, 5)

Overall for (b) and (d) I am trying to get to the varaint level of the product so please let’s have converation about how you envision this to work. Thanks.



app/src/views/Page/PageView.tsx <https://github.com/good-idea/spinellikilcollin.com/pull/83#discussion_r669220613>:

1. Is the goal here to limit Bambuser auto-playing to particular pages? If so, instead of hard-coding the slug as an environment variable, we can add an "autoplay bambuser" checkbox to collections, products, and other pages in the CMS. (This way, when they want to launch bambuser on a page other than /collections/summer-splash-sale, all they need to do is check a box in the CMS instead of having us update the environment variables.
Let’s discuss (a)




app/src/views/Page/PageView.tsx <https://github.com/good-idea/spinellikilcollin.com/pull/83#discussion_r669223817>:

2.(this would include adding a launchBambuserText field in the CMS)
Let’s discuss (a)



app/src/components/ContentBlock/HeroBlock.tsx <https://github.com/good-idea/spinellikilcollin.com/pull/83#discussion_r669224359>:

3. See the note below in PageView, i'd prefer to not tie HeroBlock up in Bambuser logic. If we want to add an option to click on a CTA within the hero block to launch the player, we can address that in a more generic way. (Also, adding CTA blocks to heros is a pending maintenance ticket, so we can implement it there and even give them the option of assigning the CTA text to launch Bambuser)
Agreed, let’s dicuss(a)



app/src/utils/fpixel.ts <https://github.com/good-idea/spinellikilcollin.com/pull/83#discussion_r669229126>:

4. Now that reportFBViewContent is called from within AnalyticsProvider, we can pass in the current variant and get the ID in a more deterministic way, instead of pulling it out of the URL. (Also, the value from ?v=... is the variant ID, not the product ID, just want to confirm that that's what you want to be using!)
Thanks Joseph for implementing this.


app/src/utils/parsing.tsx <https://github.com/good-idea/spinellikilcollin.com/pull/83#discussion_r669233636>:

5.This function was a little hard to understand ~ I added a new function getProductIdFromStorefrontId in /utils/product in my PR.
Also, node doesn't have a native atob, so that needs to be implemented manually. (It's included in /utils/product)



app/src/views/Bambuser/BambuserSample.tsx <https://github.com/good-idea/spinellikilcollin.com/pull/83#discussion_r669233881>:

6. If this is temporary / for preview purposes, can you add a // TODO comment to remove it once we launch the new feature?I have removed show.tsx and BambuserSample.tsx since we have the official links now




app/src/views/Bambuser/useBambuser.ts <https://github.com/good-idea/spinellikilcollin.com/pull/83#discussion_r669234134>:

7.Let's use getProductIdFromStorefrontId instead



app/src/views/Bambuser/useFactory.ts <https://github.com/good-idea/spinellikilcollin.com/pull/83#discussion_r669235895>:

8. I don't understand what this function does, could you explain it with some comments?

I know that the Bambuser player isn't typed, but having some type definitions in here could be helpful too.I did a url decode and base64 decode to extract the variant id. If you have a proper way to tackle this I would love to know. 



 app/src/views/Bambuser/useBambuser.ts <https://github.com/good-idea/spinellikilcollin.com/pull/83#discussion_r669237706>:

9. could you please change this to a named export as well?

done



app/src/components/SEO.tsx <https://github.com/good-idea/spinellikilcollin.com/pull/83#discussion_r669239893>:

10. See the comment in ProductView - we should not be coercing this to ShopifySourceImage as it might be undefined, in which case the line below will crash. Instead, this line could be something like:

const imageSrc = defaultSeo?.image?.w100 // will be the image URL or undefined

vs-code is complaining about the first union type does have have w100
Property 'w100' does not exist on type 'ImageType'.
  Property 'w100' does not exist on type 'Image'.ts(2339)



app/src/components/SEO.tsx <https://github.com/good-idea/spinellikilcollin.com/pull/83#discussion_r669240565>:

11. Here too we should use getProductIdFromStorefrontId and pass in the variant, instead of inferring this from the query URL. This is particularly important here for the <head> as it's rendered on the server, which (I believe) won't have access to the ?v=... parameter.
Do you have a recommendation on how to compose the json-ld format that Bambuser product scraper requires a correct variant thumbnail?



app/src/components/SEO.tsx <https://github.com/good-idea/spinellikilcollin.com/pull/83#discussion_r669241204>:

12. Generally, I prefer to use const instead of let. Could we refactor these to one-liners like:
const description = product?.sourceData?.description
const productType = product?.sourceData?.productType
Done

app/src/views/ProductDetail/ProductDetail.tsx <https://github.com/good-idea/spinellikilcollin.com/pull/83#discussion_r669241587>:
13. What is the reasoning behind this change? this will throw an error on products that do not have images. (SK is good about adding these but it's still a possibility).
If the goal is to assure Typescript that we do have an image, it would be better to allow for image to be undefined. Otherwise, with the coercion (... as ShopifySourceImage), Typescript will just "trust us" that the value is a ShopifySourceImage, and won't warn us later when it might, in reality, be undefined.

Here is an example: Sirius Silver => https://www.spinellikilcollin.com/products/sirius-silver?v=Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zMTYxOTkzMzc5ODQ5OA%3D%3D and here is the open graph meta tag <meta property="og:image" content="https://cdn.shopify.com/s/files/1/1105/2238/products/SiriusYG_Beige_3K.jpg?v=1606960115”> which is pointing to the yellow gold one.




app/src/views/ProductListing/ProductListing.tsx <https://github.com/good-idea/spinellikilcollin.com/pull/83#discussion_r669241761>:

14. Ditto with stuff from PageView, I say let's add a toggle in the CMS that lets them launch bambuser from any page.

Let’s discuss(a)

**Comment by hc-roswell** [comment]
In regards to 8, Bambuser has a factory method to “hydrate” the selected products from their dashboard. The useFactory is doing exactly that. Due to the efforts to define all the factory methods/properties with proper types would take an enormous amount of work on a code base that is subject to change on a client by client base implementation. Thanks.

hc

**Comment by hc-roswell** [comment]
Hey Joseph,
	Thank you so much for taking the time to respond, there is one point from your comment that I missed and I am showing it here. These are two separate tasks but require the same current variant id. What is the best way to grab it? Thanks.

hc


Re: prodcutID vs variantID,
	
1) Facebook Pixel “View Content” event — In the PDP view when size or color variant is selected it should be reflected in the url (v=??) and compared with product variants field to find the matching variant ID. What is the optimal way to acquire the variant id? Currently when I select size or color there is no consistent way to ensure the variant id is captured here to depict the current variant, color and size



2) Bambuser — In the dashboard, you paste in urls so Bambuser can scrape from the json-ld field to get the thumbnail and the product name ( variant name not product name) so you can see here Sirius SG and Sirius Silver are shown and with each individual thumbnail (But they are the wrong ones). Since the metafields are rendered on the server side what is the optimize way to set the json-ld field?

**Comment by good-idea** [comment]
@hc-roswell thanks for all of your comments.

I've opened a [few new issues](https://github.com/good-idea/spinellikilcollin.com/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abambuser). (tagged with `bambuser`) so we can discuss them in individual threads. 

Otherwise:

I'm adding options in Sanity to:
 - Allow a CTA to launch a bambuser video
 - Allow a page to autoplay a bambuser video
 - Create a "directory" page (that looks like `/about`) that can be used to display a list of bambuser videos (also launched by CTAs)

For the `useFactory` file --- yeah it looked pretty complicated, I understand and agree that adding types would be a big task and not worthwhile. As long as it's all working, I think we can leave it alone!

Lastly, for using the correct variant ID for fpixel and elsewhere, I can implement these changes.

I think that covers everything, if I missed something please open a new comment! Thanks :)

**Pull request merged**
